config_dic = {
    "vocab_file" :[str, ""],
    "data_file":[str, ""],
    "model_file" : [str, ""],
    "save_dir":[str, ""],
    "log_dir":[str, ""],
    "data_parallel":[bool, False],
    "max_len":[int, 512],
    "max_pred":[int, 20],
    "mask_prob":[float, 0.15],
    "d_model":[int, 512],
    "d_k":[int, 512],
    "d_v":[int, 512],
    "num_heads":[int, 8],
    "num_encoder_layers":[int, 6],
    "dim_feedforward":[int, 2048],
    "dropout_rate":[float, 0.1],
    "vocab_size":[int, None],
    "n_segments":[int, 2],
    "n_s":[int, 2],
    "H":[int, 8],
    "H_c":[int, 8],
    "tim_layers_pos":[str, ""],
    "config_file":[str, ""],
    "task" : [str, ""],
    "pretrain_file":[str, ""],
    "mode" : [str, "train"],

    "seed": [int, 3431],
    "batch_size":  [int, 32],
    "lr": [float, 1e-4],
    "n_epochs":  [int, 2],
    "warmup": [float, 0.1],
    "save_steps":  [int, 10000],
    "total_steps":  [int, 1000000]

}